.Dd $Mdocdate: October 5 2015 $
.Dt KERNEL 7
.Os
.Sh NAME
.Nm kernel
.Nd operating system kernel
.Sh SYNOPSIS
.Pa /boot/sortix.bin
.Op Fl \-no-random-seed
.Op Fl \-
.Op Ar init ...
.Sh DESCRIPTION
.Pa /boot/sortix.bin
is the operating system
.Nm kernel .
It initializes and manages the hardware to provide a multitasking computing
environment.
The kernel is a
.Xr multiboot 7
compatible executable loaded by the bootloader along with a companion
.Xr initrd 7
that contains a userland.
.Pp
The kernel extracts the initrd into the initial kernel memory root filesystem.
The specified
.Ar init
program is invoked with the given arguments, defaulting to the
.Xr init 8
at
.Pa /sbin/init
if
.Ar init
is not specified.
If the
.Nm init
is to receive any argument starting with a dash, first pass the
.Fl \-
delimiter to stop kernel option parsing.
The computer is powered off if the
.Nm init
process exits 0, rebooted if it exits 1,
halted with an complaint about an
.Nm init
fatality if it exits 2, and halted with a complaint about an unexpected exit code
otherwise.
.Pp
The options are as follows:
.Bl -tag -width "12345678"
.It Fl \-no-random-seed
Don't warn if no random seed file was loaded by the bootloader (usually from
.Pa /boot/random.seed ) .
This option is useful for live environments where this situation is unavoidable.
.El
.Sh SEE ALSO
.Xr initrd 7 ,
.Xr init 8
