LIBRARY=libdispd
LIBRARY_OBJS=\
client/library.o \
client/session.o \
client/window.o \

.include <sortix/sys.mk>
.include <template/dependencies.mk>
.include <template/headers.mk>
.include <template/library.mk>
