.Dd October 06, 2016
.Dt MEMSTAT 1
.Os
.Sh NAME
.Nm memstat
.Nd print system memory usage information
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
prints the amount of memory in use, the total amount of memory, and the
percentage of memory used.
.Sh EXIT STATUS
.Nm
will exit 0 on success and non-zero otherwise.
.Sh SEE ALSO
.Xr ps 1 ,
.Xr pstree 1 ,
.Xr memstat 2
