LIBRARY=libmount
LIBRARY_OBJS:=\
biosboot.o \
blockdevice.o \
devices.o \
crc32.o \
ext2.o \
extended.o \
filesystem.o \
gpt.o \
harddisk.o \
mbr.o \
partition.o \
uuid.o \

.include <sortix/sys.mk>
.include <template/dependencies.mk>
.include <template/headers.mk>
.include <template/library.mk>
